---
name: lint

on:
  - push
  - pull_request

env:
  DATABASE_URL: https://fake.com
  NEXTAUTH_SECRET: fake
  NEXTAUTH_URL: http://localhost:3000
  GITHUB_CLIENT_ID: fake
  GITHUB_CLIENT_SECRET: fake

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
